[package]
name = "ajuna-runtime"

authors.workspace    = true
edition.workspace    = true
homepage.workspace   = true
repository.workspace = true
version.workspace    = true

[build-dependencies]
substrate-wasm-builder = { workspace = true }

[dependencies]
# General
hex-literal = { workspace = true, optional = true }
log         = { workspace = true }
serde       = { workspace = true, features = [ "derive" ], optional = true }
smallvec    = { workspace = true }

# Parity codec
parity-scale-codec = { workspace = true }
scale-info         = { workspace = true, features = [ "derive" ] }

# Substrate
assets-common                              = { workspace = true }
frame-benchmarking                         = { workspace = true, optional = true }
frame-executive                            = { workspace = true }
frame-support                              = { workspace = true }
frame-system                               = { workspace = true }
frame-system-benchmarking                  = { workspace = true, optional = true }
frame-system-rpc-runtime-api               = { workspace = true }
frame-try-runtime                          = { workspace = true, optional = true }
pallet-assets                              = { workspace = true }
pallet-aura                                = { workspace = true }
pallet-authorship                          = { workspace = true }
pallet-balances                            = { workspace = true }
pallet-collective                          = { workspace = true }
pallet-democracy                           = { workspace = true }
pallet-identity                            = { workspace = true }
pallet-membership                          = { workspace = true }
pallet-message-queue                       = { workspace = true }
pallet-multisig                            = { workspace = true }
pallet-preimage                            = { workspace = true }
pallet-proxy                               = { workspace = true }
pallet-scheduler                           = { workspace = true }
pallet-session                             = { workspace = true }
pallet-sudo                                = { workspace = true }
pallet-timestamp                           = { workspace = true }
pallet-transaction-payment                 = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury                            = { workspace = true }
pallet-utility                             = { workspace = true }
sp-api                                     = { workspace = true }
sp-block-builder                           = { workspace = true }
sp-consensus-aura                          = { workspace = true }
sp-core                                    = { workspace = true }
sp-genesis-builder                         = { workspace = true }
sp-inherents                               = { workspace = true }
sp-io                                      = { workspace = true }
sp-offchain                                = { workspace = true }
sp-runtime                                 = { workspace = true }
sp-session                                 = { workspace = true }
sp-std                                     = { workspace = true }
sp-storage                                 = { workspace = true }
sp-transaction-pool                        = { workspace = true }
sp-version                                 = { workspace = true }

# Polkadot
pallet-xcm                    = { workspace = true }
polkadot-parachain-primitives = { workspace = true }
polkadot-runtime-common       = { workspace = true }
staging-xcm                   = { workspace = true }
staging-xcm-builder           = { workspace = true }
staging-xcm-executor          = { workspace = true }

# Cumulus
cumulus-pallet-aura-ext             = { workspace = true }
cumulus-pallet-parachain-system     = { workspace = true, features = [ "parameterized-consensus-hook" ] }
cumulus-pallet-session-benchmarking = { workspace = true }
cumulus-pallet-xcm                  = { workspace = true }
cumulus-pallet-xcmp-queue           = { workspace = true }
cumulus-primitives-aura             = { workspace = true }
cumulus-primitives-core             = { workspace = true }
cumulus-primitives-utility          = { workspace = true }
pallet-collator-selection           = { workspace = true }
parachains-common                   = { workspace = true }
staging-parachain-info              = { workspace = true }

# ORML
orml-traits = { workspace = true }
orml-vesting = { workspace = true }
orml-xcm = { workspace = true }
orml-xcm-support = { workspace = true }
orml-xtokens = { workspace = true }

# Ajuna Pallets
orml-pallets-benchmarking                 = { workspace = true, optional = true }

# integritee pallets
pallet-asset-registry = { workspace = true }
xcm-primitives = { workspace = true }

[features]
default = [ "std" ]
std = [
    "assets-common/std",
    "parity-scale-codec/std",
    "log/std",
    "scale-info/std",
    "serde/std",
    "cumulus-pallet-aura-ext/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-pallet-session-benchmarking/std",
    "cumulus-pallet-xcm/std",
    "cumulus-pallet-xcmp-queue/std",
    "cumulus-primitives-aura/std",
    "cumulus-primitives-core/std",
    "cumulus-primitives-utility/std",
    "frame-benchmarking/std",
    "frame-executive/std",
    "frame-support/std",
    "frame-system-benchmarking/std",
    "frame-system-rpc-runtime-api/std",
    "frame-system/std",
    "frame-try-runtime/std",
    "orml-traits/std",
    "orml-vesting/std",
    "orml-xcm/std",
    "orml-xcm-support/std",
    "orml-xtokens/std",
    "orml-pallets-benchmarking?/std",
    "pallet-assets/std",
    "pallet-aura/std",
    "pallet-authorship/std",
    "pallet-balances/std",
    "pallet-collective/std",
    "pallet-collator-selection/std",
    "pallet-democracy/std",
    "pallet-identity/std",
    "pallet-membership/std",
    "pallet-message-queue/std",
    "pallet-multisig/std",
    "pallet-preimage/std",
    "pallet-proxy/std",
    "pallet-scheduler/std",
    "pallet-session/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-treasury/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-transaction-payment/std",
    "pallet-utility/std",
    "pallet-xcm/std",
    "parachains-common/std",
    "staging-parachain-info/std",
    "polkadot-parachain-primitives/std",
    "polkadot-runtime-common/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-consensus-aura/std",
    "sp-core/std",
    "sp-genesis-builder/std",
    "sp-inherents/std",
    "sp-io/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-std/std",
    "sp-storage/std",
    "sp-transaction-pool/std",
    "sp-version/std",
    "staging-xcm/std",
    "staging-xcm-builder/std",
    "staging-xcm-executor/std",
    # integritee
    "pallet-asset-registry/std",
    "xcm-primitives/std",
]

runtime-benchmarks = [
    "assets-common/runtime-benchmarks",
    "cumulus-pallet-parachain-system/runtime-benchmarks",
    "cumulus-pallet-session-benchmarking/runtime-benchmarks",
    "cumulus-pallet-xcmp-queue/runtime-benchmarks",
    "cumulus-primitives-core/runtime-benchmarks",
    "cumulus-primitives-utility/runtime-benchmarks",
    "hex-literal",
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "orml-vesting/runtime-benchmarks",
    "orml-xtokens/runtime-benchmarks",
    "orml-pallets-benchmarking/runtime-benchmarks",
    "pallet-assets/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-collator-selection/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "pallet-democracy/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "pallet-membership/runtime-benchmarks",
    "pallet-message-queue/runtime-benchmarks",
    "pallet-multisig/runtime-benchmarks",
    "pallet-preimage/runtime-benchmarks",
    "pallet-proxy/runtime-benchmarks",
    "pallet-scheduler/runtime-benchmarks",
    "pallet-sudo/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-treasury/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-xcm/runtime-benchmarks",
    "parachains-common/runtime-benchmarks",
    "polkadot-parachain-primitives/runtime-benchmarks",
    "polkadot-runtime-common/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "staging-xcm-builder/runtime-benchmarks",
    "staging-xcm-executor/runtime-benchmarks",
    # integritee
    "pallet-asset-registry/runtime-benchmarks",
]

try-runtime = [
    "cumulus-pallet-aura-ext/try-runtime",
    "cumulus-pallet-parachain-system/try-runtime",
    "cumulus-pallet-xcm/try-runtime",
    "cumulus-pallet-xcmp-queue/try-runtime",
    "frame-executive/try-runtime",
    "frame-system/try-runtime",
    "frame-support/try-runtime",
    "frame-try-runtime/try-runtime",
    "orml-vesting/try-runtime",
    "orml-xcm/try-runtime",
    "orml-xtokens/try-runtime",
    "pallet-assets/try-runtime",
    "pallet-aura/try-runtime",
    "pallet-authorship/try-runtime",
    "pallet-balances/try-runtime",
    "pallet-collator-selection/try-runtime",
    "pallet-collective/try-runtime",
    "pallet-democracy/try-runtime",
    "pallet-identity/try-runtime",
    "pallet-membership/try-runtime",
    "pallet-message-queue/try-runtime",
    "pallet-multisig/try-runtime",
    "pallet-preimage/try-runtime",
    "pallet-proxy/try-runtime",
    "pallet-scheduler/try-runtime",
    "pallet-session/try-runtime",
    "pallet-sudo/try-runtime",
    "pallet-timestamp/try-runtime",
    "pallet-transaction-payment/try-runtime",
    "pallet-treasury/try-runtime",
    "pallet-utility/try-runtime",
    "pallet-xcm/try-runtime",
    "polkadot-runtime-common/try-runtime",
    "sp-runtime/try-runtime",
    "staging-parachain-info/try-runtime",
    # integritee
    "pallet-asset-registry/try-runtime",
]
