[settings]
timeout = 10000

[relaychain]
chain = "rococo-local"
default_command = "~/bin/polkadot"
default_args = ["-lparachain=debug,xcm=trace"]

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9999

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9988

[[relaychain.nodes]]
name = "charlie"
validator = true
ws_port = 9977

[[parachains]]
id = 2119
addToGenesis = true
cumulus_based = true
chain = "ajuna-rococo-local"

[[parachains.collators]]
name = "ajuna-collator01"
command = "./target/release/ajuna-node"
args = ["-lxcm=trace,runtime=debug"]
ws_port = 9944

[[parachains.collators]]
name = "ajuna-collator02"
command = "./target/release/ajuna-node"
args = ["-lxcm=trace,runtime=debug"]
ws_port = 9945

