[alias]
build-ajuna            = "build --release --no-default-features --bin ajuna-node"
build-ajuna-benchmarks = [ "build-ajuna", "--features", "runtime-benchmarks" ]

[target.'cfg(feature = "cargo-clippy")']
rustflags = [
    "-Aclippy::derive_partial_eq_without_eq",
    "-Aclippy::too_many_arguments",
    "-Aclippy::type_complexity",
    "-Aclippy::uninlined-format-args",
    "-Aclippy::unnecessary_cast",
    "-Aclippy::large_enum_variant",
]
